#ifndef FC3D_ERROR_H_INCLUDED
#define FC3D_ERROR_H_INCLUDED

#include <WF3D/error.h>

typedef enum
{
    FC3D_SUCCESS = WF3D_SUCCESS,

    FC3D_MEMORY_ERROR = WF3D_MEMORY_ERROR,
    FC3D_IMAGE_ACCESS_ERROR = WF3D_IMAGE_ACCESS_ERROR,

    FC3D_INVALID_PARAMETER = WF3D_INVALID_PARAMETER

} wf3d_error;

#endif // FC3D_ERROR_H_INCLUDED
